---
title: "Working with spatial data"
'
author: "jbroach"
date: "April 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
#install.packages("sf")
library(sf)
#install.packages("lwgeom")
library(lwgeom)
#install.packages("tidycensus")
library(tidycensus)
library(ggplot2)
library(tidyr)
if (!require(ggsn)) {install.packages("ggsn")}; library(ggsn)
if (!require(mapview)) {install.packages("mapview")}; library(mapview)
```

## Working with spatial data

```{r tidycensus load}
# this loads api key for the session
census_api_key("")

v17 <- tidycensus::load_variables(2017, "acs5", cache = T)
pdx_tracts_raw <- get_acs(geography = "tract",
                          year = 2017, 
                          variables = c("B19013_001",
                                        "B03002_003",
                                        "B01003_001"),
                          state = "OR",
                          county = c("Multnomah County"),
                          geometry = TRUE
                          ) %>% 
  select(GEOID, variable, estimate, geometry) # vars = medinc, white NH, pop
head(pdx_tracts_raw)
```

```{r tidycensus tidy}
pdx_tracts <- pdx_tracts_raw %>%
  spread(key = variable, value = estimate) %>%
  rename(medinc = B19013_001, white = B03002_003,
         pop = B01003_001) %>%
  mutate(nwhite = (pop - white) / pop, 
         area = st_area(geometry)) # area will have units!

pdx_tracts_p <- st_transform(pdx_tracts, 
                             crs = 2838) %>%
  mutate(area = st_area(geometry))
  # TODO add lookup info

plot(pdx_tracts_p)

pdx_tracts_p %>%
  arrange(desc(area))

pdx_tracts_p <- pdx_tracts_p %>%
  filter(area < units::as_units(1e8, "m^2"))

plot(pdx_tracts_p)

p <- pdx_tracts_p %>% 
  ggplot()
p + geom_sf(aes(fill = medinc)) 
p + geom_sf(aes(fill = nwhite)) +
  scale_fill_distiller(direction = -1) # flip the ramp

p + geom_sf(aes(fill = medinc), color = "lightgray") +
  scale_fill_viridis_c(option = "plasma", 
                       direction = -1, 
                       trans = "sqrt")

p + geom_sf(aes(fill = medinc), color = "lightgray") +
  coord_sf(datum = 2838) +
  scale_fill_viridis_c(option = "plasma", 
                       direction = -1) +
  xlim(232.5e4, 234e4) +
  ylim(205e3, 215e3)

p + geom_sf(aes(fill = medinc), color = "lightgray") +
  scale_fill_viridis_c(option = "plasma", 
                       direction = -1) +
  ggsn::north(pdx_tracts_p, symbol = 3, scale = 0.15) +
  ggsn::scalebar(pdx_tracts_p, dist = 4, 
                 dist_unit = "km",
                 transform = FALSE,
                 st.size = 3)
?coord_sf

```

```{r load biketown data}
source("code/fetch_biketown.R")
#getwd()
outdir <- "data/biketown/"
get_data(start = "01/2018", 
         end = "12/2018", 
         outdir = "data/biketown/")

# Stitch monthly files together for analysis
biketown_2018 <- paste0(outdir, list.files(outdir)) %>%
  lapply(read.csv, stringsAsFactors = F) %>%
  bind_rows() 

# lapply does this read.csv(file, stringsAsFactors = F)
head(biketown_2018)
# for e.g. shapefiles, just use sf::read_sf()
biketown <- biketown_2018
rm(biketown_2018)
hubs_start_sf <- biketown %>%
  group_by(StartHub) %>%
  summarize(lat = mean(StartLatitude),
            lng = mean(StartLongitude),
            starts = n()) %>%
  filter(!is.na(lat) & !is.na(lng)) %>%
  st_as_sf(coords = c("lng", "lat"),
           crs = 4326, agr = "constant") # agr is mysterious!

mapview(hubs_start_sf, zcol = "starts", legend = F,
        cex = "starts") # if basemap doesn't show
                                        # open in browser
hubs_end <- biketown %>%
  group_by(EndHub) %>%
  summarize(lat = mean(EndLatitude),
            lng = mean(EndLongitude),
            ends = n())

hubs_end_sf <- hubs_end %>%
  filter(!is.na(lat) & !is.na(lng)) %>%
  st_as_sf(coords = c("lng", "lat"),
           crs = 4326, agr = "constant") # agr is mysterious!

mapview(hubs_end_sf, zcol = "ends", legend = F,
        cex = "ends")

hubs_ratio_sf <- inner_join(hubs_start_sf,
                            hubs_end, 
                            by = c("StartHub" =
                                   "EndHub")) %>%
  mutate(starts_to_ends = starts / ends, 
         ends_to_starts = ends / starts)
m1 <- mapview(hubs_ratio_sf, zcol = "starts_to_ends",
              cex = "starts_to_ends", legend = F)
m2 <- mapview(hubs_ratio_sf, zcol = "ends_to_starts",
              cex = "ends_to_starts", legend = F)
sync(m1, m2)

```

```{r spatial joins}
hubs_start_sf_p <- hubs_start_sf %>% 
  st_transform(2838) 

hubs_start_sf_p <- hubs_start_sf_p %>%
  sf::st_join(pdx_tracts_p)

```

